### ISSUE TITLE
Scheduling problems in front of the launch desk on the iPad

### ISSUE THREAD

**Issue by 369w** [khanhduytran0/TrollPad#33]
Hello, my friend. I think I have encountered some issues while using your creative work. Can you help me? Thank you very much.
![F9580976-C285-46CC-B268-7D498F9D5BB4](https://github.com/user-attachments/assets/d4eca025-cdcc-44cf-b682-bf8bbc4bf7c9)
The application ran under the status bar, which confused me a lot.
Another issue is that when you only open one application and shrink it to its minimum size before exiting the background, it will crash,
Alright, my problem description is complete. My friend hopes you can help me

**Comment by khanhduytran0** [comment]
What you’re referring to is the floating dock. In this case, resize it larger till the dock becomes hidden.
Minimum size is undefined, I’ve only tested the minimum limit on iPhone so far so there might be another minimum limit on iPad.

**Comment by 369w** [comment]
First of all, thank you for replying to me. I am a fan of your creative work haha. I really like the setting where the size can be changed freely. I look forward to updates on your future works
