### ISSUE TITLE
Causes bootloop on iPhone Xs Max

### ISSUE THREAD

**Issue by R3tr0ooo** [khanhduytran0/TrollPad#4]
iPhone Xs Max with ios16.6.1, installed via Sileo from Bootstrap, succesfully turned on stage manager in Shortcuts, but when I disabled "Show dock" and "Show recent apps" and went horizontal, the device shuts off and goes in a bootloop.

**Comment by R3tr0ooo** [comment]
Uhhhhhhhhh......... While I was searching the web for rescue and left it to bootloop for hours, it eventually booted, like it never happened. When I unlocked it, stage manager disappeared, just normal iOS app switcher showing up.

**Comment by khanhduytran0** [comment]
Terrifying find. I got a respring loop too after disabling them. With your device suddenly going back to live, I think it just randomly tripped watchdog timeout, which will reboot your device into stock SpringBoard, and orientation set back to portrait. I haven’t tried so as I’m scared of getting permanent bootloop…

**Comment by khanhduytran0** [comment]
> reboot your device into stock SpringBoard, and orientation set back to portrait

I just risked my self to try it, indeed it bootlooped my device. Thankfully I was able to get out of it quickly, after I entered recovery mode then exited.

**Comment by R3tr0ooo** [comment]
> > reboot your device into stock SpringBoard, and orientation set back to portrait
> 
> I just risked my self to try it, indeed it bootlooped my device. Thankfully I was able to get out of it quickly, after I entered recovery mode then exited.

Yeah, I entered recovery mode and struggled for a while to decide whether or not installing the newest firmware to recover it, but thankfully I didn’t.

**Comment by khanhduytran0** [comment]
Fixed. It’s now completely safe to use as long as you use CC toggle. I’m unsure what went wrong with Show Dock disabled, but it shouldn’t be done at all, so now I hardcoded for it to always be enabled.
